version: "3.8"

services:
  mongodb:
    image: mongo:6.0.2-focal
    ports:
      - "127.0.0.1:27019:27017"
    healthcheck:
      test:
        ["CMD", "mongosh", "--eval", '''db.runCommand("ping").ok''', "--quiet"]
      interval: 2s
      timeout: 5s
      retries: 12
      start_period: 0s
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobdb
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 2s
      timeout: 5s
      retries: 12
      start_period: 0s
